version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config
      - ./auth:/etc/mosquitto/
     #- ./certs:/mosquitto/certs
    expose:
      - "1883"
      - "8883"
      - "9001"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"